### ISSUE TITLE
Date picker doesn't fit inside modal

### ISSUE THREAD

**Issue by saikksub** [davecoffin/nativescript-modal-datetimepicker#44] opened 2018-12-07 07:48 UTC
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: tns v5.0.1
- Cross-platform modules: "version": "5.0.2"
- Runtime(s): 
```
"tns-ios": {
    "version": "5.0.0"
},
"tns-android": {
    "version": "5.0.0"
}
```
- Plugin(s):
```
"dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "axios": "^0.18.0",
    "nativescript-background-http": "^3.3.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-mediafilepicker": "^2.0.14",
    "nativescript-modal-datetimepicker": "^1.1.10",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "net": "^1.0.2",
    "request": "^2.88.0",
    "tls": "0.0.1",
    "tns-core-modules": "^5.0.2",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
1. Install this plugin `tns plugin add nativescript-modal-datetimepicker`
2. Configure style inside resource folder: (As instructed in official documentation)
```
<!-- Default style for DatePicker - in spinner mode -->
<style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
    <item name="android:datePickerMode">calendar</item>
</style>
 
<!-- Default style for TimePicker - in spinner mode -->
<style name="SpinnerTimePicker" parent="android:Widget.Material.Light.TimePicker">
    <item name="android:timePickerMode">clock</item>
</style>
```
2. In your NativeScript-Vue component import and initialise dependency:
```
const ModalPicker = require("nativescript-modal-datetimepicker").ModalDatetimepicker
const picker = new ModalPicker()
```
3. on Click any method, run this code:
```
     picker.pickDate({
        title: "Select Your Birthday",
        theme: "light",
        maxDate: new Date()
      }).then(result => {
        // Note the month is 1-12 (unlike js which is 0-11)
        console.log(
          "Date is: " + result.day + "-" + result.month + "-" + result.year
        )
        var jsdate = new Date(result.year, result.month - 1, result.day);
      }).catch(error => {
        console.log("Error: " + error);
      })
```

### Is there any code involved? 
Entire component code is-
```
<template>
  <StackLayout
    class="field-item">
    <Label class="label"
      v-if="field.title"
      :text="field.title" />
    <TextField :text="date"
      @tap="selectDate"
      class="select"
      :editable="false"
      :hint="field.title" />
  </StackLayout>
</template>

<script>
const ModalPicker = require("nativescript-modal-datetimepicker").ModalDatetimepicker
const picker = new ModalPicker()

export default {
  name: 'date',
  props: ['field'],
  data () {
    return {
        field: {
            title: 'Date of Birth'
        }
    }
  }
  methods: {
    selectDate: function () {
      picker.pickDate({
        title: "Select Your Birthday",
        theme: "light",
        maxDate: new Date()
      }).then(result => {
        // Note the month is 1-12 (unlike js which is 0-11)
        console.log(
          "Date is: " + result.day + "-" + result.month + "-" + result.year
        )
        var jsdate = new Date(result.year, result.month - 1, result.day);
      }).catch(error => {
        console.log("Error: " + error);
      })
    }
  },
  }
}
</script>

```

# Final Result:
![screenshot_20181207-131555](https://user-images.githubusercontent.com/35134207/49634339-69766900-fa22-11e8-8390-6397c536dd61.png)

**Comment by saikksub** [comment] 2018-12-07 07:49
Android OS version is 7.0, Device is Moto G4 plus

**Comment by shiv19** [comment] 2018-12-11 10:34
Duplicate of #15

**Closed as completed by shiv19** 2018-12-11 10:34 UTC
