### ISSUE TITLE
Return incorrect time object on time picker

### ISSUE THREAD

**Issue by JMente** [davecoffin/nativescript-modal-datetimepicker#36] opened 2018-09-18 01:49 UTC
### Make sure to check the demo app(s) for sample usage 
Yes
### Make sure to check the existing issues in this repository 
yes
### If the demo apps cannot help and there is no issue for your problem, tell us about it
TimePicker return incorrect selection on iOS, on Android working fine but on iOS the selection don't equal the result.

### Which platform(s) does your issue occur on?
- iOS
- iOS 10.3
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2.3
- Cross-platform modules: 4.2
- Runtime(s): 4.2
- Plugin(s): 
"calendar-base": "^0.3.0",
    "is_js": "^0.9.0",
    "moment": "2.22.2",
    "nativescript-animated-circle": "^1.1.0",
    "nativescript-audio": "5.0.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-facebook": "^2.2.3",
    "nativescript-geolocation": "^4.3.0",
    "nativescript-gif": "^4.0.1",
    "nativescript-google-maps-sdk": "^2.6.1",
    "nativescript-google-maps-utils": "^0.1.3",
    "nativescript-imagepicker": "6.0.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-local-notifications": "^3.0.1",
    "nativescript-modal-datetimepicker": "1.1.4",
    "nativescript-pedometer": "^2.0.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "6.5.0",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-screenshot": "0.0.2",
    "nativescript-social-share": "^1.5.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^3.8.0",
    "nativescript-ui-listview": "^3.6.0",
    "tns-core-modules": "~4.2.0"

### Please, tell us how to recreate the issue in as much detail as possible. 
Nothing only run and get the picker for example if i select 03:00 PM the return me 09:00 AM in 24 hours format

### Is there any code involved? 
let pickerOptions = {
  is24HourView: false
};
`Picker.pickTime(pickerOptions).then((result) => {
      console.dir(result);
  });`

**Comment by shiv19** [comment] 2018-09-18 04:03
Duplicate of #35

**Closed as completed by shiv19** 2018-09-18 04:03 UTC

**Comment by JMente** [comment] 2018-10-02 22:50
Some solution? i don't have idea what's wrong, if i'm can help you please let me know.
